#ifndef PocketbaseArduino_h
#define PocketbaseArduino_h

#include <Arduino.h>
#include "PocketBase.h" // Assuming you have a PocketBase Arduino library

/**
 * @class PocketbaseCollection
 * @brief Represents a collection in the PocketBase database.
 *
 * This class provides methods to interact with a specific collection in the PocketBase database.
 * It allows retrieving, creating, updating, and deleting records in the collection.
 */
class PocketbaseCollection

    class PocketbaseCollection
{
public:
    PocketbaseCollection(PocketBase &pb, const char *collectionName)
        : pb(pb), collectionName(collectionName) {}

    /**
     * @brief Fetches a single record from a Pocketbase collection.
     *
     * This function retrieves a single record from a Pocketbase collection based on the provided record ID.
     * It allows optional parameters for expanding related fields and selecting specific fields to include in the response.
     *
     * @param recordId The ID of the record to fetch.
     * @param expand (Optional) A string specifying related fields to expand in the response.
     * @param fields (Optional) A string specifying the fields to include in the response.
     * @return The fetched record as a String object.
     */
    const String getOne(const char *recordId, const char *expand = nullptr, const char *fields = nullptr)
    {
        try
        {
            // Construct the API endpoint URL with optional expand and fields query parameters
            String apiUrl = pb.getBaseUrl() + "/api/collections/" + collectionName + "/records/" + recordId;

            if (expand != nullptr)
            {
                apiUrl += "?expand=" + String(expand);
                if (fields != nullptr)
                {
                    apiUrl += "&fields=" + String(fields);
                }
            }
            else if (fields != nullptr)
            {
                apiUrl += "?fields=" + String(fields);
            }

            // Perform the GET request to retrieve the record
            // Use your PocketBase library to make the GET request, and store the response in 'result'
            // For example, assuming pb has a getRecord method in your PocketBase library:
            String result = pb.getRecord(apiUrl);

            // Parse the result to check for error responses
            DynamicJsonDocument jsonResponse(1024); // Adjust the size based on your needs
            deserializeJson(jsonResponse, result);

            int code = jsonResponse["code"].as<int>();

            // Handle possible error responses
            if (code == 404)
            {
                // Handle 404 error
                throw PocketbaseArduinoException("Error: The requested resource wasn't found.");
            }
            else if (code == 403)
            {
                // Handle 403 error
                throw PocketbaseArduinoException("Error: Only admins can access this action.");
            }
            else
            {
                // Return the result
                return result;
            }
        }
        catch (const PocketbaseArduinoException &e)
        {
            // Handle your custom exception
            Serial.println(e.what());
        }
        catch (const std::exception &e)
        {
            // Handle other standard exceptions
            Serial.println("Exception occurred during the request: " + String(e.what()));
        }

        // Return an empty string in case of an error
        return "";
    }

    /**
     * @brief Creates a single, new record in the Pocketbase collection.
     *
     * @param jsonData The JSON data for the new record.
     * @param id (Optional) The ID of the record. If not set, it will be auto-generated by Pocketbase.
     * @param expand (Optional) A string specifying related fields to expand in the response.
     * @param fields (Optional) A string specifying the fields to include in the response.
     * @return True if the record was successfully created, false otherwise.
     */
    bool create(const char *jsonData, const char *id = nullptr, const char *expand = nullptr, const char *fields = nullptr)
    {
        try
        {
            // Perform the actual record creation
            bool success = pb.addRecord(collectionName, jsonData, id, expand, fields);

            if (!success)
            {
                // Handle the case where the record creation was not successful
                throw PocketbaseArduinoException("Error: Failed to create record.");
            }

            return success;
        }
        catch (const PocketbaseArduinoException &e)
        {
            // Handle your custom exception
            Serial.println(e.what());
        }
        catch (const std::exception &e)
        {
            // Handle other standard exceptions
            Serial.println("Exception occurred during the request: " + String(e.what()));
        }

        return false;
    }

    // TODO: REFACTOR
    const String update(const char *jsonData);

    // TODO: REFACTOR
    const String deleteRecord(const char *recordId, const char *filesToDelete[] = nullptr);

private:
    PocketBase &pb;             // Reference to the PocketBase object associated with the collection
    const char *collectionName; // The name of the collection
};

/**
 * @brief The PocketbaseArduino class represents an Arduino library for interacting with PocketBase.
 *
 * This class provides methods for creating a PocketbaseCollection object and accessing the PocketBase API.
 */
class PocketbaseArduino
{
public:
    /**
     * @brief Constructs a PocketbaseArduino object with the specified base URL.
     *
     * @param BASE_URL The base URL of the PocketBase API.
     */
    PocketbaseArduino(const char *BASE_URL)
        : pb(BASE_URL) {}

    /**
     * @brief Creates a PocketbaseCollection object for the specified collection name.
     *
     * @param collectionName The name of the collection.
     * @return PocketbaseCollection The PocketbaseCollection object.
     */
    PocketbaseCollection collection(const char *collectionName)
    {
        return PocketbaseCollection(pb, collectionName);
    }

private:
    PocketBase pb;
};

/**
 * @brief Exception class for PocketbaseArduino.
 *
 * This class represents an exception that can be thrown by the PocketbaseArduino library.
 * It inherits from the std::exception class and provides a custom error message.
 */
class PocketbaseArduinoException : public std::exception
{
public:
    /**
     * @brief Constructs a PocketbaseArduinoException object with the given error message.
     *
     * @param message The error message associated with the exception.
     */
    PocketbaseArduinoException(const std::string &message) : message(message) {}

    /**
     * @brief Returns a C-style string describing the exception.
     *
     * This function overrides the what() function of the std::exception class and returns
     * the error message associated with the exception.
     *
     * @return A C-style string describing the exception.
     */
    const char *what() const noexcept override
    {
        return message.c_str();
    }

private:
    std::string message; /**< The error message associated with the exception. */
};

#endif
